
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: basic-auth-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  tls:
  - hosts:
      - willstoney.com
    secretName: willstoney-tls
  rules:
  - host: willstoney.com
    http:
      paths:
      - path: /transmission
        backend:
          serviceName: transmission-service
          servicePort: 9091