# 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: public-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
      - willstoney.com
    secretName: willstoney-tls
  rules:
  - host: willstoney.com
    http:
      paths:
      - path: /
        backend:
          serviceName: node-service
          servicePort: 80